adapters:
  http:
    port: 8080
  postgres:
    dsn: "postgres://postgres:qwerty@localhost:5432/postgres?sslmode=disable"

services:
  auth:
    access_token:
      signing_key: "UNyi3vWZeY0QHUJgI4Qv5qVcew9JnBwJ"
      token_ttl_sec: 30
    refresh_token:
      signing_key: "VZZ1pKNG1NTAfhtubq5sHbIHiaxTtflx"
      token_ttl_sec: 120 # 2 minutes

